steps:

# Uses the docker build step to build an image called my-image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/$PROJECT_ID:$TAG_NAME', '.' ]
  env:
  - 'BUILD=$BUILD_ID'
  - 'PROJECT_ID=$PROJECT_ID'
  - 'PROJECT_NUMBER=$PROJECT_NUMBER'
  - 'REV=$REVISION_ID'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _LOCATION: us # default value
  _REPOSITORY: releases # default value

# my-image is pushed to Container Registry
images:
- '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}'


